### ISSUE TITLE
undefined: time.DateOnly

### ISSUE THREAD

**Issue by cjw414522569** [Xiaoxusheng/Go-Bat#1]
我环境的问题吗？我centos7直接yum install golang安装的go环境
依赖库也更新了
[root@fe7ec7783065 Go-Bat]# go mod tidy
go: downloading github.com/onsi/ginkgo v1.16.5
go: downloading github.com/onsi/gomega v1.18.1
go: downloading github.com/stretchr/testify v1.8.3
go: downloading github.com/uber/jaeger-client-go v2.30.0+incompatible
go: downloading github.com/frankban/quicktest v1.14.4
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/uber/jaeger-lib v2.4.1+incompatible
go: downloading go.uber.org/atomic v1.9.0
go: downloading gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/nxadm/tail v1.4.8
go: downloading github.com/google/go-cmp v0.5.9
go: downloading github.com/kr/pretty v0.3.1
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/rogpeppe/go-internal v1.9.0
[root@fe7ec7783065 Go-Bat]# go run main.go
# Go-Bat/api
api/file.go:23:34: undefined: time.DateOnly
api/file.go:24:59: undefined: time.DateOnly

**Comment by cjw414522569** [comment]
[root@fe7ec7783065 Go-Bat]# go version
go version go1.19.10 linux/amd64

**Comment by dirwgo** [comment]
你好，这个time.DateOnly是go1.21版本才有的，你可以更新一下或者将time.DateOnly替换为"2006-01-02"

**Comment by Xiaoxusheng** [comment]
你是哪个学校的，这个课表是学习通里面网页版接口，可以自己抓一下接口，每个学校的课表都是不一样的

**Comment by cjw414522569** [comment]
我自己在学习通建一个课表
